# CPE 646 Pattern Recognition Final Project
## Modulation Classification Using CNNs
### Model 2

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz

!tar -xvf spark-3.2.1-bin-hadoop3.2.tgz
!pip install -q findspark

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"
import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

from google.colab import files

spark-3.2.1-bin-hadoop3.2/
spark-3.2.1-bin-hadoop3.2/LICENSE
spark-3.2.1-bin-hadoop3.2/NOTICE
spark-3.2.1-bin-hadoop3.2/R/
spark-3.2.1-bin-hadoop3.2/R/lib/
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/DESCRIPTION
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/INDEX
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/Rd.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/features.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/links.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/package.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/Meta/vignette.rds
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/NAMESPACE
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/R/
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/R/SparkR
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/R/SparkR.rdb
spark-3.2.1-bin-hadoop3.2/R/lib/SparkR/R/SparkR.rdx
spark-3.2.1-bin-hadoop3.2/R/lib/Sp

In [ ]:
from sklearn.utils import shuffle
from sklearn.preprocessing import normalize
from sklearn.naive_bayes import MultinomialNB, CategoricalNB
import scipy.io as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

data_dir = "./drive/MyDrive/CPE646/"

train_frames = sc.loadmat(data_dir + 'TrainingRxFrames.mat')
train_labels = sc.loadmat(data_dir + 'TrainingRxLabels.mat')

valid_frames = sc.loadmat(data_dir + 'ValidationRxFrames.mat')
valid_labels = sc.loadmat(data_dir + 'ValidationRxLabels.mat')

test_frames = sc.loadmat(data_dir + 'TestRxFrames.mat')
test_labels = sc.loadmat(data_dir + 'TestRxLabels.mat')

total_data = sc.loadmat(data_dir + 'totalData_struct.mat')

In [ ]:
print("\nPrinting next trainX.\n")
print(train_frames)
print("\nPrinting next validX.\n")
print(valid_frames)
print("\nPrinting next testX.\n")
print(test_frames)
print("\nPrinting next trainY.\n")
print(train_labels)
print("\nPrinting next validY.\n")
print(valid_labels)
print("\nPrinting next testY.\n")
print(test_labels)


Printing next trainX.

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Apr 21 17:24:34 2022', '__version__': '1.0', '__globals__': [], 'rxTrainFrames': array([[[[-0.73433293,  0.40661975,  0.26263724, ...,  1.43056657,
          -0.11779913,  0.29357283],
         [-0.99518379,  1.12262192,  0.41058664, ...,  0.19228301,
          -0.10093422,  0.05780675]],

        [[-0.85662654,  0.30498608,  0.06726868, ...,  0.17782063,
           0.22213452, -0.44935864],
         [-0.62145629,  1.23494847,  0.28404234, ...,  0.41284937,
           0.16547736, -0.1603726 ]],

        [[-0.90833505,  0.09698518, -0.15276211, ..., -1.40386396,
           0.03491284, -0.17481292],
         [-0.33555202,  1.32557048,  0.15469583, ..., -0.53070444,
          -0.1256362 ,  0.01835499]],

        ...,

        [[ 1.38139364,  0.5723435 ,  1.52669444, ..., -0.07693506,
          -0.01234699,  0.13134079],
         [ 0.27414485, -0.02216188, -0.52293875, ..., -0.21305149,
       

In [ ]:
import sklearn.preprocessing
## x1 feature = inphase signal
## x2 feature = quadrature signal
train_x = train_frames['rxTrainFrames']
nb_X = train_x[0]
nb_X = np.reshape(nb_X, (88000, 2048))
nb_X = normalize(nb_X, axis=0)
print(np.shape(nb_X))

train_x = np.reshape(train_x, (88000, 2, 1024, 1)).astype("float32")
train_y = train_labels['rxTrainY']
train_y = train_y[0]
train_y = train_y[0][6]
nb_y = np.reshape(train_y, (88000,))
train_y = train_y - 1
train_y = tf.keras.utils.to_categorical(train_y, num_classes=11, dtype='float32')
train_x, train_y = shuffle(train_x, train_y)

valid_x = valid_frames['rxValidFrames']
#valid_x = valid_x[0]
valid_x = np.reshape(valid_x, (11000, 2, 1024, 1)).astype("float32")
valid_y = valid_labels['rxTestY']
valid_y = valid_y[0]
valid_y = valid_y[0][6]
valid_y = valid_y - 1
valid_y = tf.keras.utils.to_categorical(valid_y, num_classes=11, dtype='float32')
valid_x, valid_y = shuffle(valid_x, valid_y)

test_x = test_frames['rxTestFrames']
#test_x = test_x[0]
test_x = np.reshape(test_x, (11000, 2, 1024, 1)).astype("float32")
test_y = test_labels['TestRxLabels'][0]
test_y = test_y[0][6]
test_y = test_y - 1
test_y = tf.keras.utils.to_categorical(test_y, num_classes=11, dtype='float32')

#test_y = np.reshape(1, 88000)

#train_x = train_x.melt(id_vars=train_x[2])
print("\nPrinting next trainX.\n")
print(train_x)
print("\nPrinting next trainY.\n")
print(train_y)
print("\nPrinting next validX.\n")
print(valid_x)
print("\nPrinting next validY.\n")
print(valid_y)
print("\nPrinting next testX.\n")
print(test_x)
print("\nPrinting next testY.\n")
print(test_y)
print(train_x.shape)

(88000, 2048)

Printing next trainX.

[[[[ 1.0131797 ]
   [ 1.1250964 ]
   [-0.56818384]
   ...
   [ 0.15661354]
   [-0.54551995]
   [-0.73045814]]

  [[-0.9121873 ]
   [ 0.84241945]
   [-0.9796077 ]
   ...
   [-0.11227161]
   [-0.75979793]
   [ 1.1878828 ]]]


 [[[ 0.00883198]
   [ 0.7665038 ]
   [ 0.08480228]
   ...
   [ 0.17699826]
   [-0.10418639]
   [ 0.93281853]]

  [[-0.30965978]
   [ 0.44487542]
   [ 1.2847846 ]
   ...
   [ 0.35682482]
   [ 0.92434365]
   [-0.16597469]]]


 [[[ 0.96144426]
   [ 0.76157975]
   [-0.63076407]
   ...
   [-0.72366226]
   [ 0.03843232]
   [-0.71779245]]

  [[ 0.46633428]
   [-0.79939085]
   [-0.8667867 ]
   ...
   [-0.21940674]
   [ 1.2445495 ]
   [-0.7515417 ]]]


 ...


 [[[-1.2369083 ]
   [ 0.4043204 ]
   [ 0.1100907 ]
   ...
   [ 0.8666174 ]
   [-0.20343949]
   [ 0.63987   ]]

  [[ 0.8429761 ]
   [ 0.42607   ]
   [ 0.59470797]
   ...
   [-1.1801814 ]
   [ 0.71231973]
   [ 1.221411  ]]]


 [[[-0.6910936 ]
   [-0.6237839 ]
   [ 0.90754324]
   ...
 

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, 1, activation='relu', padding='same', 
                                 input_shape=(2,1024,1)))
model.add(tf.keras.layers.MaxPooling2D(1,2))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(64, 1, activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPooling2D(1,2))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(128, 1, activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPooling2D(1,2))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.AveragePooling2D((1,2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(11, activation='softmax'))


In [ ]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(train_x, train_y, batch_size=256, epochs=12, validation_data=(valid_x, valid_y))


Epoch 1/12
344/344 [==============================] - 241s 696ms/step - loss: 2.6717 - accuracy: 0.0956 - val_loss: 2.4973 - val_accuracy: 0.0933
Epoch 2/12
261/344 [=====================>........] - ETA: 57s - loss: 2.3702 - accuracy: 0.1377

In [ ]:
results = model.evaluate(test_x, test_y)
print(results)

344/344 [==============================] - 1s 4ms/step - loss: 3.1061 - accuracy: 0.0955
[3.1061015129089355, 0.0955454558134079]


In [ ]:
from sklearn.cluster import kmeans_plusplus
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

# Generate sample data
n_samples = 4000
n_components = 4

X, y_true = make_blobs(
    n_samples=n_samples, centers=n_components, cluster_std=0.60, random_state=0
)
X = X[:, ::-1]

# Calculate seeds from kmeans++
centers_init, indices = kmeans_plusplus(X, n_clusters=4, random_state=0)

# Plot init seeds along side sample data
plt.figure(1)
colors = ["#4EACC5", "#FF9C34", "#4E9A06", "m"]

for k, col in enumerate(colors):
    cluster_data = y_true == k
    plt.scatter(X[cluster_data, 0], X[cluster_data, 1], c=col, marker=".", s=10)

plt.scatter(centers_init[:, 0], centers_init[:, 1], c="b", s=50)
plt.title("K-Means++ Initialization")
plt.xticks([])
plt.yticks([])
plt.show()

In [ ]:
print(nb_X.min())
clf = CategoricalNB()
clf.fit(nb_X, nb_y)
print(clf.score(nb_X, nb_y))

0.010769154314691498
